export const clothesMock = [
	{
		id: 1,
		name: "Maison Kitsune Brown & Off-White Chiru Sneakers",
		type: "shoes",
		color: "brown",
		style: "casual",
		img: "/clothes/maison-kitsune-brown-and-off-white-chiru-sneakers.avif",
	},
	{
		id: 2,
		name: "Maison Kitsune Off-White Cafe Kitsune Sweatshirt",
		type: "top",
		color: "off-white",
		style: "casual",
		img: "/clothes/maison-kitsune-off-white-cafe-kitsune-sweatshirt.avif",
	},
	{
		id: 3,
		name: "Maison Kitsune Pink Bold Fox Head Patch Regular Cardigan",
		type: "top",
		color: "pink",
		style: "cute",
		img: "/clothes/maison-kitsune-pink-bold-fox-head-patch-regular-cardigan.avif",
	},
	{
		id: 4,
		name: "The Row Beige Eglitta Trousers",
		type: "bottom",
		color: "beige",
		style: "formal",
		img: "/clothes/the-row-beige-eglitta-trousers.avif",
	},
	{
		id: 5,
		name: "The Row Beige Jazor Sweater",
		type: "top",
		color: "beige",
		style: "cozy",
		img: "/clothes/the-row-beige-jazor-sweater.avif",
	},
	{
		id: 6,
		name: "The Row Gray Claudine Maxi Dress",
		type: "dress",
		color: "gray",
		style: "elegant",
		img: "/clothes/the-row-gray-claudine-maxi-dress.avif",
	},
	{
		id: 7,
		name: "The Row Off-White Medium N/S Park Tote",
		type: "accessory",
		color: "off-white",
		style: "casual",
		img: "/clothes/the-row-off-white-medium-n-s-park-tote.avif",
	},
	{
		id: 8,
		name: "The Row White Jashi Bucket Hat",
		type: "accessory",
		color: "white",
		style: "cute",
		img: "/clothes/the-row-white-jashi-bucket-hat.avif",
	},
	{
		id: 9,
		name: "The Row White Tikea Maxi Dress",
		type: "dress",
		color: "white",
		style: "elegant",
		img: "/clothes/the-row-white-tikea-maxi-dress.avif",
	},
];
