export const clothesMock = [
	{
		name: "Versace Jeans Couture Black Logo Minidress",
		type: "dress",
		color: "black",
		style: "chic, elegant, formal",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/versace-jeans-couture-black-logo-minidress.avif",
	},
	{
		name: "Pleats Please Issey Miyake Beige June New Colorful Basics 4 Maxi Dress",
		type: "dress",
		color: "beige",
		style: "chic, elegant",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/pleats-please-issey-miyake-beige-june-new-colorful-basics-4-maxi-dress.avif",
	},
	{
		name: "Willy Chavarria Black Ruff Rider Track Jacket",
		type: "jacket",
		color: "black",
		style: "casual, street",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/willy-chavarria-black-ruff-rider-track-jacket.avif",
	},
	{
		name: "Willy Chavarria Red Bad Boy Track Jacket",
		type: "jacket",
		color: "red",
		style: "casual, street",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/willy-chavarria-red-bad-boy-track-jacket.avif",
	},
	{
		name: "Fear of God Essentials Black Soft Rib Biker Shorts",
		type: "bottom",
		color: "black",
		style: "casual, comfy, sporty",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/fear-of-god-essentials-black-soft-rib-biker-shorts.avif",
	},
	{
		name: "Fear of God Essentials Black Waffle Leggings",
		type: "bottom",
		color: "black",
		style: "casual, comfy, sporty",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/fear-of-god-essentials-black-waffle-leggings.avif",
	},
	{
		name: "Fear of God Essentials Black 90s Fleece Zip-Up Hoodie",
		type: "top",
		color: "black",
		style: "casual, street",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/fear-of-god-essentials-black-90s-fleece-zip-up-hoodie.avif",
	},
	{
		name: "Fear of God Essentials Black Classic Fit Long Sleeve T-Shirt",
		type: "top",
		color: "black",
		style: "casual, street",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/fear-of-god-essentials-black-classic-fit-long-sleeve-t-shirt.avif",
	},
	{
		name: "Fear of God Essentials Gray Classic Fit Long Sleeve T-Shirt",
		type: "top",
		color: "gray",
		style: "casual, street",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/fear-of-god-essentials-gray-classic-fit-long-sleeve-t-shirt.avif",
	},
	{
		name: "Lisa Yang Gray Bria Tank Top",
		type: "top",
		color: "gray",
		style: "casual, comfy",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/lisa-yang-gray-bria-tank-top.avif",
	},
	{
		name: "Lemaire Off-White Souris Flat Classic Derbys",
		type: "shoes",
		color: "off-white",
		style: "classic, formal",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/lemaire-off-white-souris-flat-classic-derbys.avif",
	},
	{
		name: "Nicole Saldana Black Anna Tall Boots",
		type: "shoes",
		color: "black",
		style: "casual, chic, street",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/nicole-saldana-black-anna-tall-boots.avif",
	},
	{
		name: "Nicole Saldana Black Sarah Heeled Sandals",
		type: "shoes",
		color: "black",
		style: "chic, street",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/nicole-saldana-black-sarah-heeled-sandals.avif",
	},
];
