export const clothesMock = [
	{
		name: "Courrèges Black Hybrid 01 Sunglasses",
		type: "sunglasses",
		color: "black",
		style: "edgy, stylish, street",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/courreges-black-hybrid-01-sunglasses.avif",
	},
	{
		name: "Courrèges Black One Shoulder Crepe Jersey Midi Dress",
		type: "dress",
		color: "black",
		style: "stylish, chic, elegant",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/courreges-black-one-shoulder-crepe-jersey-midi-dress.avif",
	},
	{
		name: "Courrèges Black Reedition Vinyl Miniskirt",
		type: "skirt",
		color: "black",
		style: "edgy, stylish",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/courreges-black-reedition-vinyl-miniskirt.avif",
	},
	{
		name: "Courrèges Black Shadow Sunglasses",
		type: "sunglasses",
		color: "black",
		style: "edgy, stylish, street",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/courreges-black-shadow-sunglasses.avif",
	},
	{
		name: "Courrèges Black Signature Contrast T-Shirt",
		type: "top",
		color: "black",
		style: "casual",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/courreges-black-signature-contrast-t-shirt.avif",
	},
	{
		name: "Courrèges Black Undressed Rib Knit Minidress",
		type: "dress",
		color: "black",
		style: "edgy, stylish, street",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/courreges-black-undressed-rib-knit-minidress.avif",
	},
	{
		name: "Courrèges Blue Cocoon Denim Jacket",
		type: "jacket",
		color: "blue",
		style: "edgy, stylish, street",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/courreges-blue-cocoon-denim-jacket.avif",
	},
	{
		name: "Courrèges Off-White Slim Holy Bag",
		type: "bag",
		color: "off-white",
		style: "edgy, stylish, street",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/courreges-off-white-slim-holy-bag.avif",
	},
	{
		name: "Dries Van Noten Brown Square Toe Loafers",
		type: "shoes",
		color: "brown",
		style: "clean-fit, chic, stylish",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/dries-van-noten-brown-square-toe-loafers.avif",
	},
	{
		name: "Dries Van Noten Red Suede Sneakers",
		type: "shoes",
		color: "red",
		style: "casual, stylish",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/dries-van-noten-red-suede-sneakers.avif",
	},
	{
		name: "Dries Van Noten White and Beige Suede Sneakers",
		type: "shoes",
		color: "white, beige",
		style: "casual, chic",
		img: "https://sabohqpppsoecsgzxrnz.supabase.co/storage/v1/object/public/clothes-images/dries-van-noten-white-and-beige-suede-sneakers.avif",
	},
];
